### ISSUE TITLE
Crash on start under wayland

### ISSUE THREAD

**Issue by EysseW** [dvershinin/green-recorder#18]
Hi! According to the Arch wiki, your app supports wayland. I, however, installed it through the AUR and got this error: 
```
$ green-recorder
You are recording on: wayland
Traceback (most recent call last):
  File "/usr/bin/green-recorder", line 33, in <module>
    sys.exit(load_entry_point('green-recorder==3.2.10', 'gui_scripts', 'green-recorder')())
  File "/usr/bin/green-recorder", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/recorder/__init__.py", line 1, in <module>
    from .recorder import main
  File "/usr/lib/python3.10/site-packages/recorder/recorder.py", line 112, in <module>
    GNOMEScreencast = bus.get('org.gnome.Shell.Screencast', '/org/gnome/Shell/Screencast')
  File "/usr/lib/python3.10/site-packages/pydbus/proxy.py", line 44, in get
    ret = self.con.call_sync(
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Shell.Screencast was not provided by any .service files (2)
```

**Comment by sistematico** [comment]
Same for me:
```
$ green-recorder 
You are recording on: wayland
```

**Comment by dhasial** [comment]
Over a year later, I'm getting the exact same error

```
You are recording on: wayland
Traceback (most recent call last):
  File "/usr/bin//green-recorder", line 33, in <module>
    sys.exit(load_entry_point('green-recorder==3.2.10', 'gui_scripts', 'green-recorder')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin//green-recorder", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/recorder/__init__.py", line 1, in <module>
    from .recorder import main
  File "/usr/lib/python3.11/site-packages/recorder/recorder.py", line 112, in <module>
    GNOMEScreencast = bus.get('org.gnome.Shell.Screencast', '/org/gnome/Shell/Screencast')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydbus/proxy.py", line 44, in get
    ret = self.con.call_sync(
          ^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable (2)
```

**Comment by dvershinin** [comment]
@dhasial @EysseW It is a distro's problem. Please submit an issue in their respective bug tracker. Documented details in [known issues](https://github.com/dvershinin/green-recorder/blob/master/README.md#known-issues).
