### ISSUE TITLE
Unable to install on fedora 32

### ISSUE THREAD

**Issue by sujil02** [dvershinin/green-recorder#6]
```
sudo yum -y install https://extras.getpagespeed.com/release-latest.rpm
Last metadata expiration check: -3 days, 14:24:05 ago on Tue 16 Jun 2020 02:38:19 PM EDT.
release-latest.rpm                                                                                                                                                                                             26 kB/s |  14 kB     00:00    
Error: 
 Problem: conflicting requests
  - nothing provides epel-release needed by getpagespeed-extras-release-10-15.noarch
(try to add '--skip-broken' to skip uninstallable packages)

```
```
sudo yum install green-recorder
Last metadata expiration check: -3 days, 14:24:18 ago on Tue 16 Jun 2020 02:38:19 PM EDT.
No match for argument: green-recorder
Error: Unable to find a match: green-recorder

```

**Comment by dvershinin** [comment]
@sujil02 can you try it like the following:

```
# installs RPMFusion repository, for FFmpeg (skip if you already have it)
sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf install https://github.com/dvershinin/green-recorder/releases/download/3.2.6/green-recorder-3.2.6-1.fc32.noarch.rpm
```

Unfortunately, in my limited testing it gave an error. When launching `green-recorder` in Terminal:

```
Traceback (most recent call last):
  File "/usr/bin/green-recorder", line 11, in <module>
    load_entry_point('green-recorder==3.2.4', 'gui_scripts', 'green-recorder')()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.8/site-packages/recorder/__init__.py", line 1, in <module>
    from .recorder import main
  File "/usr/lib/python3.8/site-packages/recorder/recorder.py", line 92, in <module>
    bus = SessionBus()
  File "/usr/lib/python3.8/site-packages/pydbus/bus.py", line 60, in SessionBus
    return bus_get(Bus.Type.SESSION)
  File "/usr/lib/python3.8/site-packages/pydbus/bus.py", line 19, in bus_get
    return Gio.bus_get_sync(type, None).pydbus
gi.repository.GLib.Error: g-exec-error-quark: Failed to execute child process “dbus-launch” (No such file or directory) (8)
```

Restarting `dbus` causes log out but then it works. Hopefully, it's related only to the way I'm testing (Virtualbox). Let me know if you have different results.
